server:
  port: 8085
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: temporal-samples
  banner:
    location: banner.txt
  # temporal specific configs
  temporal:
    namespace: default
    connection:
      target: 127.0.0.1:7233
    # (Note following configuration are not set by default but serve more as reference)
    #    workers:
    #      - task-queue: DemoTaskQueue
    #        capacity:
    #          max-concurrent-workflow-task-pollers: 6
    #          max-concurrent-activity-task-pollers: 6
    #        rate-limits:
    #          max-worker-activities-per-second: 3
    #          max-task-queue-activities-per-second: 3
    #    workflow-cache:
    #      max-instances: 10
    #      max-threads: 10
    workersAutoDiscovery:
      packages: io.temporal.samples.springboot
  # data source config for some samples that need it
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: temporal
    password: temporal
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true